version: '3.8'

services:
  postgres:
    container_name: "reactive-postgres"
    image: postgres
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: coursesshopreactive

  redis-local:
    container_name: "reactive-redis"
    image: redis
    ports:
      - "6379:6379"    
